#! /usr/bin/env python3

import argparse
import pathlib
import sys

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--data', type=pathlib.Path)
    parser.add_argument('--output-dir', type=pathlib.Path)
    parser.add_argument('--file-name', type=str)
    parser.add_argument('--var-name', type=str)
    args = parser.parse_args()

    data = args.data.read_bytes()
    length = len(data)

    header = args.output_dir / (args.file_name + '.generated.h')

    content = ""
    content += "// Generated by source/spargel/render/gen.py\n"
    content += "// Do not modify\n"
    content += "\n"
    content += "#include <spargel/base/types.h>\n"
    content += "\n"
    content += "inline constexpr u8 " + args.var_name + "[] = {\n"
    for i, b in enumerate(data):
        content += f"0x{b:02x}, "
        if (i + 1) % 12 == 0:
            content += "\n"
    content += "\n};\n\n"

    with open(header, "w") as f:
        f.write(content)

    return 0

if __name__ == '__main__':
    sys.exit(main())
