import argparse
import shlex
from pathlib import Path

parser = argparse.ArgumentParser()
parser.add_argument("--output", type=Path)
parser.add_argument("--gen-dir", type=Path)
parser.add_argument("--rsp", type=Path)
args = parser.parse_args()

output = args.gen_dir / args.output

with open(args.rsp, "r") as rsp_file:
    defs = shlex.split(rsp_file.read())

flags = []

for flag in defs:
    equals_index = flag.index('=')
    key = flag[:equals_index]
    value = flag[equals_index + 1:]

    if value == 'true':
        value = '1'
    elif value == 'false':
        value = '0'

    flags.append((key, str(value)))

with open(output, "w") as output_file:
    output_file.write("#pragma once\n\n")
    output_file.write("// Generated by //gn/script/write_autoconfig.py\n\n")
    for pair in flags:
        key, value = pair
        output_file.write(f"#define {key} {value}\n")
